### ISSUE TITLE
"An error occured while loading AccesoriesPlus"

### ISSUE THREAD

**Issue by dx512ii** [Destructor-Ben/Accessories-Plus#1]
![image](https://user-images.githubusercontent.com/94173166/172049716-f01251ab-15a3-44c4-8e7d-18792bebb280.png)
this happened when i tried to reload mods in my tml - stable 1.4 with this mod only, almost similar happening with wings slot too

**Comment by Destructor-Ben** [comment]
I'll have a look and update the mod when its fixed.

**Comment by Destructor-Ben** [comment]
You're using the preview version of tModLoader, but the mod was developed for the stable version of tModLoader, if you want to use the mod you'll have to change to the stable version, since mods break quite frequently in the preview version.
