### ISSUE TITLE
Found a bug with tooltip text

### ISSUE THREAD

**Issue by vizthex123** [Destructor-Ben/Accessories-Plus#2]
I assume it applies to everything that uses your custom Copper Bars recipe group, but I found this at like 3 AM so I didn't do a thorough check.

![tooltip](https://github.com/Destructor-Ben/Accessories-Plus/assets/31721920/1735bf78-8e09-4683-ad0f-60efa689630c)

**Comment by Destructor-Ben** [comment]
Should be a one line fix, thanks for letting me know. I believe it affects all recipe groups as well.

**Comment by Destructor-Ben** [comment]
Fixed, but probably won't be published for a while

**Comment by vizthex123** [comment]
> Fixed, but probably won't be published for a while

noice, thanks for fixing it.
